apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-secrets
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/agent-inject-secret-db-creds: "secretos/data/basedatos"
    vault.hashicorp.com/agent-inject-template-db-creds: |
      MYSQL_USER={{ .Data.data.MYSQL_USER }}
      MYSQL_PASSWORD={{ .Data.data.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD={{ .Data.data.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE={{ .Data.data.MYSQL_DATABASE }}
    vault.hashicorp.com/role: "webapp"
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
      - name: MYSQL_USER
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['vault.hashicorp.com/agent-inject-template-db-creds']
      - name: MYSQL_PASSWORD
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['vault.hashicorp.com/agent-inject-template-db-creds']
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['vault.hashicorp.com/agent-inject-template-db-creds']
      - name: MYSQL_DATABASE
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['vault.hashicorp.com/agent-inject-template-db-creds']