apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-secrets
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "webapp"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/agent-inject-secret-db: "secretos/data/basedatos"
    vault.hashicorp.com/agent-inject-template-db.env: |
      {{- with secret "secretos/data/basedatos" }}
      #!/bin/bash
      export MYSQL_USER={{ .Data.data.MYSQL_USER }}
      export MYSQL_PASSWORD={{ .Data.data.MYSQL_PASSWORD }}
      export MYSQL_ROOT_PASSWORD={{ .Data.data.MYSQL_ROOT_PASSWORD }}
      export MYSQL_DATABASE={{ .Data.data.MYSQL_DATABASE }}
      {{- end }}
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      command:
        - "/bin/sh"
        - "-c"  # Esto indica que el siguiente comando es un script de shell
      args:
        - "source /vault/secrets/db.env && docker-entrypoint.sh mysqld"  # Comando final para iniciar MySQL
