apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-pod-secrets
  namespace: default # Cambia el namespace si es necesario
data:
  MYSQL_USER: ""

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-secrets
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/agent-inject-secret-MYSQL_USER: "secretos/data/basedatos"
    vault.hashicorp.com/agent-inject-template-MYSQL_USER: |
      {{- with secret "secretos/data/basedatos" -}}
      {{ .Data.data.MYSQL_USER }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-MYSQL_PASSWORD: "secretos/data/basedatos"
    vault.hashicorp.com/agent-inject-template-MYSQL_PASSWORD: |
      {{- with secret "secretos/data/basedatos" -}}
      {{ .Data.data.MYSQL_PASSWORD }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-MYSQL_ROOT_PASSWORD: "secretos/data/basedatos"
    vault.hashicorp.com/agent-inject-template-MYSQL_ROOT_PASSWORD: |
      {{- with secret "secretos/data/basedatos" -}}
      {{ .Data.data.MYSQL_ROOT_PASSWORD }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-MYSQL_DATABASE: "secretos/data/basedatos"
    vault.hashicorp.com/agent-inject-template-MYSQL_DATABASE: |
      {{- with secret "secretos/data/basedatos" -}}
      {{ .Data.data.MYSQL_DATABASE }}
      {{- end }}
    vault.hashicorp.com/role: "webapp"
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
      - name: MYSQL_USER
        valueFrom:
          configMapKeyRef:
            name: mysql-pod-secrets # El ConfigMap será inyectado por Vault Agent
            key: MYSQL_USER
      - name: MYSQL_PASSWORD
        value: "/vault/secrets/MYSQL_PASSWORD"
      - name: MYSQL_ROOT_PASSWORD
        value: "/vault/secrets/MYSQL_ROOT_PASSWORD"
      - name: MYSQL_DATABASE
        value: "/vault/secrets/MYSQL_DATABASE"